### ISSUE TITLE
How are u rendering custom nodes into the graph view?

### ISSUE THREAD

**Issue by BlitzVI** [jackvonhouse/custom-node-size#1]
Hey! Could you please explain to me how you are rendering custom nodes in the graph view? I'd like to know as i want to develop my own plugin that adds custom nodes to the graph view but i can't seem to figure out how. Any help is greatly appreciated!. You can contact me on my discord aswell as im much more active on discord. My discord id is bltz_v. Thank you!

**Comment by jackvonhouse** [comment]
@BlitzVI Hi! I don't render node directly. I just modify the `weight` param, which is then rendered with Obsidian using the `pixi.js` library.

If you want to add custom node, you must inspect `renderer` structure. To do this, press `Ctrl+Shift+i` to open the console. Then open the graph and execute this code in the console:
```js
this.app.workspace.getLeavesOfType("graph").first().view.renderer
```

I can also recommend [this](https://github.com/natefrisch01/Graph-Link-Types) repo, which renders label in lines between nodes.

**Comment by BlitzVI** [comment]
> @BlitzVI Hi! I don't render node directly. I just modify the `weight` param, which is then rendered with Obsidian using the `pixi.js` library.
> 
> If you want to add custom node, you must inspect `renderer` structure. To do this, press `Ctrl+Shift+i` to open the console. Then open the graph and execute this code in the console:
> 
> ```js
> this.app.workspace.getLeavesOfType("graph").first().view.renderer
> ```
> 
> I can also recommend [this](https://github.com/natefrisch01/Graph-Link-Types) repo, which renders label in lines between nodes.

**Comment by BlitzVI** [comment]
> @BlitzVI Hi! I don't render node directly. I just modify the `weight` param, which is then rendered with Obsidian using the `pixi.js` library.
> 
> If you want to add custom node, you must inspect `renderer` structure. To do this, press `Ctrl+Shift+i` to open the console. Then open the graph and execute this code in the console:
> 
> ```js
> this.app.workspace.getLeavesOfType("graph").first().view.renderer
> ```
> 
> I can also recommend [this](https://github.com/natefrisch01/Graph-Link-Types) repo, which renders label in lines between nodes.

ah alr i've already messed around with asking the exact same question in that repo but i still dont understand how i can add my own nodes just by looking at the src. If you could help me setup this renderer thing, i could try and mess around with it myself. Also is there any documentation that you are following? i have no clue what getleaf and such does. Also mb for making the issue ugly i dont use github much. Thank you for the reply!

**Comment by jackvonhouse** [comment]
@BlitzVI It would be better if you write exactly what your task is. What kind of nodes do you want to create?
